name: "Component Tests"

on:
  repository_dispatch:
    types:
      - component-tests

jobs:
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Component Tests
        run: |
          chmod +x ./run-component-tests.sh
          ./run-component-tests.sh
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: allure-results-component_mock
          path: allure-results/
          if-no-files-found: error
